### ISSUE TITLE
Migrate up and down multiple statements

### ISSUE THREAD

**Issue by seaninmar** [kruxia/sqly#1]
Some database engines (like sqlite3) don't support multiple statements in a single execution block. For these engines, we need the ability to execute multiple statements in a migration; without that, we have to create multiple migrations. Update the migration engine so that `up` and `dn` blocks that are lists instead of strings are executed sequentially within a single transaction.

**Comment by seanharrison** [comment]
Issue has been resolved -- migrations now have a list of SQL strings instead of a single one.
